[package]
name = "multiples_of_3_and_5"
version = "0.1.0"
authors = ["rainbowsec"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
