[package]
name = "largest_prime_factor"
version = "0.1.0"
authors = ["rainbowsec <59576967+rainbowsec@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
